# Generated by Django 6.0.1 on 2026-03-01 16:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0006_order_orderitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(
                fields=['expected_return_date'], name='order_exp_ret_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='order_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(
                fields=['supplier', 'status'], name='order_sup_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-order_date'], name='order_date_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(
                fields=['status', 'expected_return_date'], name='order_status_date_idx'),
        ),
    ]
