# Generated by Django 6.0.1 on 2026-03-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0007_order_order_exp_ret_idx_order_order_status_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='received_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Rempli lors de la réception de la commande', null=True, verbose_name='Quantité reçue'),
        ),
    ]
