# Generated by Django 6.0.1 on 2026-03-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0008_orderitem_received_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='invoiced_quantity',
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name='Quantité facturée'),
        ),
    ]
