# Generated by Django 6.0.1 on 2026-03-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0009_orderitem_invoiced_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('delayed', 'En retard'), ('completed', 'Terminée'), ('partial', 'Terminée/partielle')], default='pending', max_length=20, verbose_name='Statut'),
        ),
    ]
