# Generated by Django 6.0.3 on 2026-03-05 18:48

from django.db import migrations


def migrate_associated_items(apps, schema_editor):
    """
    Copie les associations de Supplier.associated_items vers Item.suppliers
    pour ne pas perdre de données avant la suppression du champ.
    """
    Supplier = apps.get_model('supplier', 'Supplier')
    for supplier in Supplier.objects.prefetch_related('associated_items').all():
        for item in supplier.associated_items.all():
            item.suppliers.add(supplier)


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0010_alter_order_status'),
    ]

    operations = [
        migrations.RunPython(
            migrate_associated_items,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='associated_items',
        ),
    ]
