# Generated by Django 6.0.1 on 2026-01-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0005_alter_supplier_associated_items'),
        ('supply', '0004_remove_item_quantity_item_available_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='suppliers',
            field=models.ManyToManyField(blank=True, related_name='items', to='supplier.supplier'),
        ),
    ]
