# Generated by Django 6.0.1 on 2026-01-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0005_item_suppliers'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stock_entry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
