# Generated by Django 6.0.1 on 2026-03-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0006_item_stock_entry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='excess_quantity',
            field=models.PositiveIntegerField(
                default=0, help_text='Quantité excédentaire'),
        ),
        migrations.AddField(
            model_name='item',
            name='last_inventory_date',
            field=models.DateTimeField(
                blank=True, help_text='Date du dernier inventaire', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='last_inventory_quantity',
            field=models.PositiveIntegerField(
                default=0, help_text='Quantité lors du dernier inventaire'),
        ),
    ]
