# Generated by Django 6.0.1 on 2026-03-01 16:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0007_order_order_exp_ret_idx_order_order_status_idx_and_more'),
        ('supply', '0007_item_excess_quantity_item_last_inventory_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': [
                'name'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(
                fields=['available_quantity'], name='item_avail_qty_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(
                fields=['outside_quantity'], name='item_out_qty_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(
                fields=['excess_quantity'], name='item_excess_qty_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['is_available'],
                               name='item_is_avail_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(
                fields=['category', 'name'], name='item_cat_name_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['-created_at'],
                               name='item_created_idx'),
        ),
    ]
