# Generated by Django 6.0.1 on 2026-03-01 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0008_alter_item_options_item_item_avail_qty_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='inventories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inventaire',
                'verbose_name_plural': 'Inventaires',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('counted_quantity', models.PositiveIntegerField(default=0)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='entries', to='supply.inventory')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='inventory_entries', to='supply.item')),
            ],
            options={
                'verbose_name': "Entrée d'inventaire",
                'verbose_name_plural': "Entrées d'inventaire",
                'unique_together': {('inventory', 'item')},
            },
        ),
    ]
