# Generated by Django 6.0.1 on 2026-03-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0009_inventory_inventoryentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryentry',
            name='outside_quantity_snapshot',
            field=models.PositiveIntegerField(
                default=0, help_text="Quantité chez le fournisseur au moment de l'inventaire"),
        ),
        migrations.AlterField(
            model_name='inventoryentry',
            name='counted_quantity',
            field=models.PositiveIntegerField(
                default=0, help_text="Quantité comptée sur site lors de l'inventaire"),
        ),
    ]
