"""
Django settings for LaundryWatcher project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import sys

# Build paths inside the project like this: BASE_DIR / 'subdir'.
if getattr(sys, 'frozen', False):
    BASE_DIR = Path(sys._MEIPASS)
else:
    BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*1u+7)8@cbfnm_!$cz2k3-atlqfi2*39xzwgd4fpgzgk1(yh0k'

# SECURITY WARNING: don't run with debug turned on in production!
if getattr(sys, 'frozen', False):
    DEBUG = False
    ALLOWED_HOSTS = ['*']
else:
    DEBUG = True
    ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'crispy_bootstrap5',
    'authentication',
    'core',
    'supply',
    'supplier',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'authentication.middleware.AccountExpirationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'LaundryWatcher.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'LaundryWatcher' / 'templates',
            BASE_DIR / 'authentication' / 'templates',
            BASE_DIR / 'core' / 'templates',
            BASE_DIR / 'supply' / 'templates',
            BASE_DIR / 'supplier' / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LaundryWatcher.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if getattr(sys, 'frozen', False):
    # Determine a writable directory for data (Database and Logs)
    # We use %APPDATA%/SupplyManager normally.
    # Fallback to executable dir if APPDATA not set (unlikely on Windows).
    app_data_dir = Path(os.environ.get('APPDATA')) / 'SupplyManager'
    app_data_dir.mkdir(parents=True, exist_ok=True)
    
    db_path = app_data_dir / 'db.sqlite3'
    log_path = app_data_dir / 'debug.log'

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': db_path,
        }
    }
    
    # Configure logging to catch errors in production
    # Force creation of log file
    try:
        if not log_path.exists():
            log_path.touch()
    except Exception:
        pass

    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'formatters': {
            'verbose': {
                'format': '{levelname} {asctime} {module} {message}',
                'style': '{',
            },
        },
        'handlers': {
            'file': {
                'level': 'ERROR',
                'class': 'logging.FileHandler',
                'filename': str(log_path),
                'formatter': 'verbose',
            },
            # Add a catch-all specific handler
            'file_debug': {
                'level': 'DEBUG',
                'class': 'logging.FileHandler',
                'filename': str(log_path),
                'formatter': 'verbose',
            },
        },
        'loggers': {
            'django': {
                'handlers': ['file'],
                'level': 'ERROR',
                'propagate': True,
            },
            # Root logger to catch everything
            '': {
                'handlers': ['file_debug'],
                'level': 'INFO', # Get info level logs too
            },
        },
    }
    
# FINAL DEBUGGING CONFIGURATION
if getattr(sys, 'frozen', False):
    DEBUG = True
    ALLOWED_HOSTS = ['*']
    
    # Logging setup
    app_data_dir = Path(os.environ.get('APPDATA')) / 'SupplyManager'
    log_path = app_data_dir / 'runtime_error.log'
    
    # Ensure log file exists
    try:
        log_path.parent.mkdir(parents=True, exist_ok=True)
        with open(log_path, 'a') as f:
            f.write("\n--- NEW SESSION ---\n")
    except Exception:
        pass

    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'formatters': {
            'verbose': {
                'format': '{levelname} {asctime} {name} {message}',
                'style': '{',
            },
        },
        'handlers': {
            'file': {
                'level': 'DEBUG',
                'class': 'logging.FileHandler',
                'filename': str(log_path),
                'formatter': 'verbose',
                'mode': 'a',
            },
            'console': {
                'level': 'DEBUG',
                'class': 'logging.StreamHandler',
                'formatter': 'verbose',
            }
        },
        'loggers': {
            'django': {
                'handlers': ['file', 'console'],
                'level': 'DEBUG',
                'propagate': True,
            },
            '': {
                'handlers': ['file', 'console'],
                'level': 'DEBUG',
            }
        },
    }
else:
    # Development settings
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Email configuration (Development)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'noreply@laundrywatcher.com'

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr-FR'

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

CRISPY_ALLOW_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

STATIC_URL = 'static/'

if getattr(sys, 'frozen', False):
    STATIC_ROOT = BASE_DIR / 'static'
    # Use simple storage to avoid 500 errors if manifest is missing or mismatch
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'
    # When frozen, we don't use STATICFILES_DIRS, preventing conflict with STATIC_ROOT
    STATICFILES_DIRS = []
else:
    STATIC_ROOT = BASE_DIR / 'staticfiles'
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
    STATICFILES_DIRS = [BASE_DIR / 'static']

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom user model
AUTH_USER_MODEL = 'authentication.User'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

# Email configuration
# Pour le développement, on affiche les emails dans la console
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# Pour la production, décommentez et configurez les lignes suivantes :
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'votre_email@gmail.com'
# EMAIL_HOST_PASSWORD = 'votre_mot_de_passe_app'
# DEFAULT_FROM_EMAIL = 'LaundryWatcher <noreply@laundrywatcher.com>'

