# Generated by Django 6.0.1 on 2026-01-20 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='date_end_contract',
            field=models.DateField(blank=True, null=True, verbose_name='Date fin contrat'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_start_contract',
            field=models.DateField(blank=True, null=True, verbose_name='Date début contrat'),
        ),
        migrations.AddField(
            model_name='user',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='still_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DIRECTOR', 'Responsable'), ('CREW', 'Équipe')], default='CREW', max_length=15),
        ),
    ]
