# Generated by Django 6.0.1 on 2026-01-20 22:21

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Un utilisateur avec ce nom existe déjà.'}, max_length=150, unique=True, validators=[authentication.models.UsernameWithSpacesValidator()]),
        ),
    ]
