# Generated by Django 6.0.1 on 2026-03-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Utilisateur',
                     'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='user_role_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['still_active'],
                               name='user_active_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(
                fields=['date_end_contract'], name='user_end_contract_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(
                fields=['role', 'still_active'], name='user_role_active_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(
                fields=['role', 'date_end_contract'], name='user_role_contract_idx'),
        ),
    ]
